version: "3"
services:
  mysql:
    container_name: mysql
    image: mysql
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
    environment:
      MYSQL_ROOT_PASSWORD: 123456789,
      MYSQL_DATABASE: company
    volumes:
       - ~/my-mysql/sql-scripts:/docker-entrypoint-initdb.d/
    networks:
        testing_net:
            ipv4_address: 172.28.35.1
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
        testing_net:
            ipv4_address: 172.28.35.2
  web1:
    # replace username/repo:tag with your name and image details
    image: server1-sa
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "3001:3000"
    networks:
      testing_net:
            ipv4_address: 172.28.35.7
    environment:
      - PORT=8787
      - DATABASE_HOST=172.28.35.1
      - DATABASE_PASSWORD=123456789
    depends_on:
      - mysql
      
networks:
    testing_net:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16